ECHO ON
REM ----------------------------------------------------------------------------------------
REM 			Builds the Umkehr Fortran code on Windows 64 bit using the PGI Fortran Community Edition
REM 
REM THIS SCRIPT SHOULD BE RUN FROM THE "PGI CMD" console so the PGI Fortran compiler (18.10) is properly enabled.
REM This package also requires that you have Visual Studio 2017 (Community edition or better) installed.
REM 
REM 1) This script builds the library which is linked by the Python setup.py when building the python wheel
REM   
REM 2) Note that the setup.py script is generated by the linux ./configure from setup.py.in. This includes
REM    setting the version number in setup.py.in. If necessary you can manually edit setup.py.in and write it to setup.py. 
REM 
REM -----------------------------------------------------------------------------------------
REM 
REM CALL "C:\PROGRA~1\PGI\win64\18.10\pgi_dos.bat"
ECHO ON

pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -c sources\matinvn.f          -o matinvn.obj
pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -c sources\sasco3.f           -o sasco3.obj
pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -c sources\spline.f           -o spline.obj
pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -c sources\stndrd.f           -o stndrd.obj
pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -c sources\umkehr_interface.f -o umkehr_interface.obj
pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -c sources\umkv8.f            -o umkv8.obj
pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -c sources\decodev4.for       -o decodev4.obj
REM pgfortran -fast -i4 -r8 -Mfixed -Mr8 -Mr8intrinsics -Mnomain -Msave -Bdynamic -Mmakedll -Xlinker /VERBOSE:Lib  -L C:\Users\nickl\Anaconda3\libs -o _umkehr_if.pyd matinvn.obj sasco3.obj spline.obj stndrd.obj umkehr_interface.obj umkv8.obj decodev4.obj  umkehr_if_wrap.obj umkehr_if.obj umkehr_io.obj

ar -rv umkehr_codelib.lib matinvn.obj sasco3.obj spline.obj stndrd.obj umkehr_interface.obj umkv8.obj decodev4.obj 
del *.obj
pip wheel ./ -w ./wheelhouse

del umkehr_codelib.lib
dir .\wheelhouse\*.whl

ECHO OFF
ECHO                  
ECHO                  ********        **    **
ECHO                **        **      **   ** 
ECHO                **        **      ** ** 
ECHO                **        **      *** *
ECHO                **        **      **   **
ECHO                **        **      **    **
ECHO                  ********        **     **
ECHO ON
ECHO  	    The build process for the libraries worked!
EXIT /B 0

