# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_umkehr_if')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_umkehr_if')
    _umkehr_if = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_umkehr_if', [dirname(__file__)])
        except ImportError:
            import _umkehr_if
            return _umkehr_if
        try:
            _mod = imp.load_module('_umkehr_if', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _umkehr_if = swig_import_helper()
    del swig_import_helper
else:
    import _umkehr_if
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _umkehr_if.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self) -> "PyObject *":
        return _umkehr_if.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _umkehr_if.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _umkehr_if.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _umkehr_if.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _umkehr_if.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _umkehr_if.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _umkehr_if.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _umkehr_if.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _umkehr_if.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _umkehr_if.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _umkehr_if.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _umkehr_if.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _umkehr_if.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _umkehr_if.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _umkehr_if.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _umkehr_if.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _umkehr_if.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringList, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _umkehr_if.StringList_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _umkehr_if.StringList___nonzero__(self)

    def __bool__(self) -> "bool":
        return _umkehr_if.StringList___bool__(self)

    def __len__(self) -> "std::list< std::string >::size_type":
        return _umkehr_if.StringList___len__(self)

    def __getslice__(self, i: 'std::list< std::string >::difference_type', j: 'std::list< std::string >::difference_type') -> "std::list< std::string,std::allocator< std::string > > *":
        return _umkehr_if.StringList___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _umkehr_if.StringList___setslice__(self, *args)

    def __delslice__(self, i: 'std::list< std::string >::difference_type', j: 'std::list< std::string >::difference_type') -> "void":
        return _umkehr_if.StringList___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _umkehr_if.StringList___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::list< std::string >::value_type const &":
        return _umkehr_if.StringList___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _umkehr_if.StringList___setitem__(self, *args)

    def pop(self) -> "std::list< std::string >::value_type":
        return _umkehr_if.StringList_pop(self)

    def append(self, x: 'std::list< std::string >::value_type const &') -> "void":
        return _umkehr_if.StringList_append(self, x)

    def empty(self) -> "bool":
        return _umkehr_if.StringList_empty(self)

    def size(self) -> "std::list< std::string >::size_type":
        return _umkehr_if.StringList_size(self)

    def swap(self, v: 'StringList') -> "void":
        return _umkehr_if.StringList_swap(self, v)

    def begin(self) -> "std::list< std::string >::iterator":
        return _umkehr_if.StringList_begin(self)

    def end(self) -> "std::list< std::string >::iterator":
        return _umkehr_if.StringList_end(self)

    def rbegin(self) -> "std::list< std::string >::reverse_iterator":
        return _umkehr_if.StringList_rbegin(self)

    def rend(self) -> "std::list< std::string >::reverse_iterator":
        return _umkehr_if.StringList_rend(self)

    def clear(self) -> "void":
        return _umkehr_if.StringList_clear(self)

    def get_allocator(self) -> "std::list< std::string >::allocator_type":
        return _umkehr_if.StringList_get_allocator(self)

    def pop_back(self) -> "void":
        return _umkehr_if.StringList_pop_back(self)

    def erase(self, *args) -> "std::list< std::string >::iterator":
        return _umkehr_if.StringList_erase(self, *args)

    def __init__(self, *args):
        this = _umkehr_if.new_StringList(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'std::list< std::string >::value_type const &') -> "void":
        return _umkehr_if.StringList_push_back(self, x)

    def front(self) -> "std::list< std::string >::value_type const &":
        return _umkehr_if.StringList_front(self)

    def back(self) -> "std::list< std::string >::value_type const &":
        return _umkehr_if.StringList_back(self)

    def assign(self, n: 'std::list< std::string >::size_type', x: 'std::list< std::string >::value_type const &') -> "void":
        return _umkehr_if.StringList_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _umkehr_if.StringList_resize(self, *args)

    def insert(self, *args) -> "void":
        return _umkehr_if.StringList_insert(self, *args)

    def pop_front(self) -> "void":
        return _umkehr_if.StringList_pop_front(self)

    def push_front(self, x: 'std::list< std::string >::value_type const &') -> "void":
        return _umkehr_if.StringList_push_front(self, x)

    def reverse(self) -> "void":
        return _umkehr_if.StringList_reverse(self)
    __swig_destroy__ = _umkehr_if.delete_StringList
    __del__ = lambda self: None
StringList_swigregister = _umkehr_if.StringList_swigregister
StringList_swigregister(StringList)


def set_umkehr_inputfolder(inputfolder: 'char const *') -> "bool":
    return _umkehr_if.set_umkehr_inputfolder(inputfolder)
set_umkehr_inputfolder = _umkehr_if.set_umkehr_inputfolder

def get_output_stream(unit: 'int') -> "std::list< std::string,std::allocator< std::string > > const &":
    return _umkehr_if.get_output_stream(unit)
get_output_stream = _umkehr_if.get_output_stream

def get_input_stream(unit: 'int') -> "std::list< std::string,std::allocator< std::string > > const &":
    return _umkehr_if.get_input_stream(unit)
get_input_stream = _umkehr_if.get_input_stream

def set_umkehr_input_filename(unit: 'int', fullname: 'char const *') -> "void":
    return _umkehr_if.set_umkehr_input_filename(unit, fullname)
set_umkehr_input_filename = _umkehr_if.set_umkehr_input_filename

def analyze_umkehr(inputfilename: 'char const *', KBN: 'int') -> "bool":
    return _umkehr_if.analyze_umkehr(inputfilename, KBN)
analyze_umkehr = _umkehr_if.analyze_umkehr
# This file is compatible with both classic and new-style classes.


